name: "Newcastle Cognition Lab"
author: "newcastlecognitionlab@gmail.com"
title: Newcastle Cognition Lab
description: "Newcastle Cognition Lab site for information about members, publications and software"

url: "https://newcastlecl.github.io/"
repo_url: "https://github.com/NewcastleCL/NewcastleCL.github.io"

# Twitter username (used by jekyll-seo-tag)
twitter:
  username: NewcastleCogLab

# GitHub Metadata -- https://github.com/jekyll/github-metadata
repository: NewcastleCL/NewcastleCL.github.io
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
